#thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.mode=LEGACYHTML5
server.port=8888
#mybatis
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.opzpy123.opzpy123.bean
#数据库连接
spring.datasource.username=root
spring.datasource.password=opzpy123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/opzpy123?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone= Asia/Shanghai 
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
#log日志
logging.level.com.opzpy123.mypeojectdemo=debug
logging.file.name=opzpy123.log
logging.file.path=/
#aliyunOss对象存储
aliyun.oss.endpoint=oss-cn-hangzhou.aliyuncs.com
aliyun.oss.bucketName =opzpy123
aliyun.oss.AccessKey=LTAI4FeHivGsYQ1GerngQLBx
aliyun.oss.AccessKeySecret=XjHKlWKGQgC0FiJcOzXU30kzocYETu
#文件大小限制
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
